changes and updates according new design of some components
arduino/arc pull request #3
Opened 2022-01-17 15:37 UTC by netergart

### Added
 - toggle component  via @fstasi 
 
 ### Fixed
 - inputs and select styles
 - fixed reset method and allow default HTML5 attributes in the input
 - allow using children components inside radio/checkbox components
  
 ### Changed
 - updated checkbox UI color
 - added more style variants in the select component
 
 P.S.
This can be big PR because I transferred all changes from the old repo and I need all changed inside classroom #4
All next PR will be correct 1 feature for 1 PR

2022-01-17 15:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/arduino/arc?pullRequest=3) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/arduino/arc?pullRequest=3) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: fstasi<br/>:x: netergart<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/arduino/arc?pullRequest=3) it.</sub>

2022-02-11 09:52 UTC, Serjlee commented
@fstasi have you the chance to review this in the near future?

2022-02-18 15:15 UTC, fstasi requested changes
I'd go with react 16 if possible. the pr overall is good

2022-03-04 13:58 UTC, lukdog commented on src/components/checkbox/CheckboxGroupItem.tsx
> +      {props.children}
Fixed in [b81e445](https://github.com/arduino/arc/pull/3/commits/b81e4453186fb68a69e5ea7092129a583860822f)

2022-03-04 13:58 UTC, lukdog commented on src/components/checkbox/RadioGroupItem.tsx
> +      {props.children}
Fixed in [b81e445](https://github.com/arduino/arc/pull/3/commits/b81e4453186fb68a69e5ea7092129a583860822f)

2022-03-04 16:34 UTC, fstasi approved these changes

2022-03-04 16:36 UTC, merged